truncate trigger_campaign_trigger_campaign_condition;
truncate trigger_campaign_condition_params;
truncate trigger_campaign_condition_fulfillment;
truncate trigger_campaign_user;
truncate trigger_campaign_user_blacklist;
delete from trigger_campaign_fulfillment where id;
delete from condition_param where id;
delete from trigger_campaign_condition where id;
delete from trigger_campaign where id;